version: "3.9"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  wordpress:
    depends_on:
      - db
    image: wordpress:6.2-php8.2-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', false );
        define( 'WP_MEMORY_LIMIT', '256M' );
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - wp_data:/var/www/html
    ports:
      - "80:80"
    networks:
      - wpnet

networks:
  wpnet:

volumes:
  db_data:
  wp_data:
